In [1]:
import pandas as pd
import os

In [2]:
movie = pd.read_csv("/Users/michael/Documents/UCSB_2017-2018/PSTAT 134/134MHCP/MovieGenre.csv", encoding='latin-1')

In [3]:
movie.head(5)

,imdbId,Imdb Link,Title,IMDB Score,Genre,Poster
0,114709,http://www.imdb.com/title/tt114709,Toy Story (1995),8.3,Animation|Adventure|Comedy,https://images-na.ssl-images-amazon.com/images...
1,113497,http://www.imdb.com/title/tt113497,Jumanji (1995),6.9,Action|Adventure|Family,https://images-na.ssl-images-amazon.com/images...
2,113228,http://www.imdb.com/title/tt113228,Grumpier Old Men (1995),6.6,Comedy|Romance,https://images-na.ssl-images-amazon.com/images...
3,114885,http://www.imdb.com/title/tt114885,Waiting to Exhale (1995),5.7,Comedy|Drama|Romance,https://images-na.ssl-images-amazon.com/images...
4,113041,http://www.imdb.com/title/tt113041,Father of the Bride Part II (1995),5.9,Comedy|Family|Romance,https://images-na.ssl-images-amazon.com/images...

In [4]:
df = pd.get_dummies(movie['Genre'])
# df = merge.drop('Genre', axis=1)
# df = merge['Genre'].str.join(sep='').str.get_dummies(sep='|')
# df['title'] = merge.Title
# df

In [5]:
df['title'] = movie.Title

In [6]:
cols = df.columns.tolist()

In [7]:
cols = cols[-1:] + cols[:-1]

In [8]:
df = df[cols]

In [9]:
df.head(5)

,title,Action,Action|Adventure,Action|Adventure|Animation,Action|Adventure|Biography,Action|Adventure|Comedy,Action|Adventure|Crime,Action|Adventure|Drama,Action|Adventure|Family,Action|Adventure|Fantasy,...,War|Short,War|Western,Western,Western|Action,Western|Action|Drama,Western|Adventure,Western|Comedy,Western|Crime,Western|Drama,Western|Sci-Fi|Thriller
0,Toy Story (1995),0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Jumanji (1995),0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,Grumpier Old Men (1995),0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Waiting to Exhale (1995),0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Father of the Bride Part II (1995),0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
df2 = movie['Genre'].str.join(sep='').str.get_dummies(sep='|')

In [11]:
df2['title'] = movie.Title

In [12]:
df2.head(5)

,Action,Adult,Adventure,Animation,Biography,Comedy,Crime,Documentary,Drama,Family,...,Reality-TV,Romance,Sci-Fi,Short,Sport,Talk-Show,Thriller,War,Western,title
0,0,0,1,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Toy Story (1995)
1,1,0,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,Jumanji (1995)
2,0,0,0,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,Grumpier Old Men (1995)
3,0,0,0,0,0,1,0,0,1,0,...,0,1,0,0,0,0,0,0,0,Waiting to Exhale (1995)
4,0,0,0,0,0,1,0,0,0,1,...,0,1,0,0,0,0,0,0,0,Father of the Bride Part II (1995)

In [13]:
cols = df2.columns.tolist()
cols = cols[-1:] + cols[:-1]
df = df2[cols]

In [14]:
df.head(5)

,title,Action,Adult,Adventure,Animation,Biography,Comedy,Crime,Documentary,Drama,...,News,Reality-TV,Romance,Sci-Fi,Short,Sport,Talk-Show,Thriller,War,Western
0,Toy Story (1995),0,0,1,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Jumanji (1995),1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Grumpier Old Men (1995),0,0,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,0,0
3,Waiting to Exhale (1995),0,0,0,0,0,1,0,0,1,...,0,0,1,0,0,0,0,0,0,0
4,Father of the Bride Part II (1995),0,0,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,0,0

In [15]:
df2 = df.sort_values('title')
df2.head(5)

,title,Action,Adult,Adventure,Animation,Biography,Comedy,Crime,Documentary,Drama,...,News,Reality-TV,Romance,Sci-Fi,Short,Sport,Talk-Show,Thriller,War,Western
30809,#1 Cheerleader Camp (2010),0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35694,#Horror (2015),0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
39297,#Pellichoopulu (2016),0,0,0,0,0,1,0,0,1,...,0,0,1,0,0,0,0,0,0,0
24316,#chicagoGirl: The Social Network Takes on a Di...,1,0,0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
28049,"$1,000 on the Black (1966)",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [54]:
df2.reset_index(drop = True)

,title,Action,Adult,Adventure,Animation,Biography,Comedy,Crime,Documentary,Drama,...,News,Reality-TV,Romance,Sci-Fi,Short,Sport,Talk-Show,Thriller,War,Western
0,#1 Cheerleader Camp (2010),0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,#Horror (2015),0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,#Pellichoopulu (2016),0,0,0,0,0,1,0,0,1,...,0,0,1,0,0,0,0,0,0,0
3,#chicagoGirl: The Social Network Takes on a Di...,1,0,0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
4,"$1,000 on the Black (1966)",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
5,"$100,000 for Ringo (1965)",0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
6,$5 a Day (2008),0,0,0,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
7,$50K and a Call Girl: A Love Story (2014),1,0,1,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,$9.99 (2008),0,0,0,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
9,$ellebrity (2012),0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
10,'49-'17 (1917),0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
11,'71 (2014),1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
12,'D' (2005),0,0,0,0,0,0,1,0,1,...,0,0,0,0,0,0,0,1,0,0
13,'Doc' (1971),0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
14,'Fun on a Week-End' (1947),0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,'G' Men (1935),0,0,0,0,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
16,'Gung Ho!': The Story of Carlson's Makin Islan...,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
17,'Hellboy': The Seeds of Creation (2004),0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
18,'I Know Where I'm Going!' (1945),0,0,0,0,0,0,0,0,1,...,0,0,1,0,0,0,0,0,0,0
19,'Master Harold'... and the Boys (1985),0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
20,'Neath the Arizona Skies (1934),0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
21,'Pimpernel' Smith (1941),0,0,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
22,'R Xmas (2001),0,0,0,0,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
23,'Rameau's Nephew' by Diderot (Thanx to Dennis ...,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,'Round Midnight (1986),0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
25,"'Sheba, Baby' (1975)",1,0,0,0,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
26,'Til There Was You (1997),0,0,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,0,0
27,'Tis the Season for Love (2015),0,0,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,0,0
28,'Twas the Night (2001),0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,'Twas the Night Before Christmas (1974),0,0,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40078,ÌÛ trois on y va (2015),0,0,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,0,0
40079,Ìàa brÌÈle (2006),0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
40080,Ìàa commence par la fin (2010),0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
40081,Ìàogunluk (2010),0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
40082,Ìãgget Ì_r lÌ¦st! En hÌ´rdkokt saga (1975),0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
40083,ÌãkkilÌ_htÌ¦ (2016),0,0,0,0,0,1,0,0,1,...,0,0,1,0,0,0,0,0,0,0
40084,Ìälisa (1995),0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
40085,Ìäperdument (2016),0,0,0,0,1,0,0,0,1,...,0,0,1,0,0,0,0,0,0,0
40086,Ìävocateur: The Morton Downey Jr. Movie (2012),0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
40087,Ìävolution (2015),0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
40088,Ìö arrivato mio fratello (1985),0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
40089,Ìö stato il figlio (2012),0,0,0,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
40090,Ìö tornato Sabata... hai chiuso un'altra volta...,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
40091,Ì÷rnens Ìüje (1997),1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
40092,åÁA volar joven! (1947),0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
40093,åÁAsu Mare! (2013),0,0,0,0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
40094,åÁAsu Mare! 2 (2015),0,0,0,0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
40095,åÁCuba SÌ_! (1961),0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
40096,åÁMÌÁtalo! (1970),1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
40097,åÁQuÌ© hacer! (1972),0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
40098,åÁVivan las antÌ_podas! (2011),0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
40099,ía commence aujourd'hui (1999),0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
40100,íloge de l'amour (2001),0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
40101,íxtasis (1996),0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
40102,íÊon Flux (2005),1,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
40103,íînibus 174 (2002),0,0,0,0,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
40104,íó Nous la Libertí© (1931),0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
40105,íó Tout de Suite (2004),0,0,0,0,0,0,1,0,1,...,0,0,1,0,0,0,0,0,0,0
40106,íó la folie... pas du tout (2002),0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
40107,íó la mode (1993),0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [65]:
df2.loc[df2['title'] == '$5 a Day (2008)']

,title,Action,Adult,Adventure,Animation,Biography,Comedy,Crime,Documentary,Drama,...,News,Reality-TV,Romance,Sci-Fi,Short,Sport,Talk-Show,Thriller,War,Western
16472,$5 a Day (2008),0,0,0,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0